### PR TITLE
Replaces minilp with microlp

### PR DESCRIPTION
**Pull request by Specy**

### CODE REVIEW

**Comment by lovasoa** [comment]
Could you enable issues in the microlp repo ?

**Comment by lovasoa** [comment]
If you are motivated to maintain and improve microlp in the long run, a good first step could be to add support for MILP (add integer variables). The original author already made an implementation using branch & bound, but they only put in in the exemples folder instead of integrating it to the library itself: https://github.com/Specy/microlp/blob/4dc2acc643689730a8451ba9bb303c6437bb16f3/examples/tsp.rs

Integer problems are very common and a tiny implementation like the one in minilp would be very welcome for embedded use cases, such as the wasm.

**Comment by lovasoa** [comment]
> Sure, also watchout, I hadn't yet added the possibility to specify both minilp and microlp feature flags in the PR

I am adding it

**Comment by Specy** [comment]
> If you are motivated to maintain and improve microlp in the long run

I would work on it, my only issue is lack on knowledge in OR, I only have university level knowledge of it, I don't feel like I'm knowledgeable enough in the field to work on it properly, but branch and bound could be doable and I'd love to have MILP in the library. Do make an issue on the repo to keep track of it

**Pull request merged**
