### PR TITLE
add interface to set HiGHS option

### PR DESCRIPTION
**Pull request by lucidfrontier45**
I added an API to set [HiGHS options](https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html) to the `HighsProblem` struct. This solves #18 .

Currently the API is not safe enough, we can still add invalid key and value type. For example `set_option("time_limit".to_string(), 10)` will panic when `solve` method is called. Perhaps I should add explicit APIs like `set_time_limit(value: f64)`. What do you think?

### CODE REVIEW

**Review by lovasoa — CHANGES_REQUESTED** [review]
Hi, and thanks for the PR !

> Perhaps I should add explicit APIs like set_time_limit(value: f64). What do you think?

Yes, that's how it should work

**Comment by lovasoa** [comment]
If you want to add support for time limits, we should store an explicit `time_limit: Option<f64>` and not a hashmap<String, Anything>

**Comment by lucidfrontier45** [comment]
> If you want to add support for time limits, we should store an explicit `time_limit: Option<f64>` and not a hashmap<String, Anything>

No, I don't want to just use `time_limit`. I also want to use other options like `presolve`, `parallel` etc. There are 45 options in total. Writing specific setter for each of them sounds too redundant. That's why I wrote a generic setter in the current PR.

**Comment by lovasoa** [comment]
I think you should have specific setters and tests for each of them. And even for each combination of them where it's relevant. It's the only way to guarantee we will not panic at runtime.

**Comment by lucidfrontier45** [comment]
@lovasoa 

I re-wrote the PR to implement explicit setters for a few HiGHS options.

- presolve
- solver
- parallel
- time_limit
- threads

**Comment by lucidfrontier45** [comment]
@lovasoa How about this PR? Is there anything I have to do to merge it?

**Review by lovasoa — APPROVED** [review]

**Pull request merged**
