### PR TITLE
add clarabel wasm feature flag

### PR DESCRIPTION
**Pull request by Specy**
Adds the possibility to specify `wasm` feature flag to clarabel

### CODE REVIEW

**Review by lovasoa — CHANGES_REQUESTED** [review]
See this previous comment on the same topic: https://github.com/rust-or/good_lp/pull/58#issuecomment-2245466365

If you need this just for yourself, see: https://stackoverflow.com/questions/59994525/how-do-i-specify-features-for-a-sub-dependency-in-cargo

**Comment by Specy** [comment]
> If you need this just for yourself, see: https://stackoverflow.com/questions/59994525/how-do-i-specify-features-for-a-sub-dependency-in-cargo

I've tried setting: 
```
good_lp = { version = "1.8.1", features = ['clarabel'], default-features = false }
clarabel = { version = "*", features = ['wasm']} #also tried to put version as 0.9.0
```
but this does not seem to enable the feature flag.

What kind of test for CI were you thinking? simple build under wasm32-unknown-unknown?

**Comment by lovasoa** [comment]
Ideally we would run wasm tests too

**Comment by Specy** [comment]
I could also include `minilp` to the WASM tests if you want

**Review by lovasoa — COMMENTED** [review]
This looks good !

Can we mention the new feature in the readme, maybe in the clarabel section ?

Then we can merge this !

**Comment by Specy** [comment]
I have absolutely no idea what that error is! Probably some mismatch in versions, I'll check later when I'm back home.

Should I add a new column in the table for things that support wasn't or add it as a new section note?

**Comment by lovasoa** [comment]
I opened an issue on the clarabel side: https://github.com/oxfordcontrol/Clarabel.rs/issues/134

It looks like the "wasm" feature should be removed. Clarabel could just compile for wasm natively if dependencies and conditional compilation were set up properly on their side: https://github.com/oxfordcontrol/Clarabel.rs/issues/134

This does not prevent us to merge this pr on our side, to prevent future changes that would break wasm compatibility in good_lp itself.

**Comment by Specy** [comment]
> It looks like the "wasm" feature should be removed. Clarabel could just compile for wasm natively if dependencies and conditional compilation were set up properly on their side: [oxfordcontrol/Clarabel.rs#134](https://github.com/oxfordcontrol/Clarabel.rs/issues/134)
I'll try to make a PR there too to fix it 

I'll also add wasm support as a new column to the table to show which solvers are able to be compiled to wasm. If in the future it will be able to compile to wasm-unknown-emscripten I could also include [soplex](https://github.com/scipopt/soplex-sys/issues/3) so this seems like a flexible solution. What do you think?

**Comment by Specy** [comment]
Ok the CI should be fixed now, just had to install node

**Review by lovasoa — APPROVED** [review]

**Comment by lovasoa** [comment]
Thank you for your contribution, @Specy !

**Pull request merged**
